import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import WeatherProvider from "./comps/data"
import DateProvider from "./comps/time"
import InfoMode from "./comps/darkmode"
import Lang from "./comps/lang-param"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "meteo",
  description: "Generated by salmen",
  icons: { icon: '/logo.png' },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Lang>
        <WeatherProvider>
          <DateProvider>
            <InfoMode>
            {children}
            </InfoMode>
          </DateProvider>
        </WeatherProvider>
        </Lang>
        
      </body>
    </html>
  );
}
